#!/usr/bin/env node
// Bundles `tools/_core/theme.ts` to a single IIFE script that every HTML
// page loads via `<script src="tools/shared.bundle.js">`. Theme ships as
// a plain script-tag global because:
//   - the inline no-FOUC IIFE in each HTML `<head>` needs the `data-theme`
//     attribute set synchronously before paint, and
//   - the module's event-listener side-effects (BroadcastChannel,
//     `storage`, `visibilitychange`) must run before the SPA's
//     `<script type="module">` (which is implicitly deferred) parses.
//
// IIFE format keeps the bundle a plain script tag (no module / no
// `module.exports`) so `vm.runInThisContext` and a `<script>` element
// both evaluate it the same way. `globalName` collects `_core/theme.ts`'s
// named exports into `__plottrTheme`; the synthetic
// `Object.assign(globalThis, __plottrTheme)` footer (appended below)
// makes `getTheme` / `setTheme` / `toggleTheme` reachable from inline
// scripts in `benchmark.html` and `privacy.html` without each `_core/*`
// module having to write to `globalThis` itself.

const fs = require("fs");
const path = require("path");
const esbuild = require("esbuild");

const TOOLS_DIR = path.join(__dirname, "..", "tools");
const OUT_FILE = path.join(TOOLS_DIR, "shared.bundle.js");
const ENTRY = path.join(TOOLS_DIR, "_core/theme.ts");

function buildBundle() {
  const result = esbuild.buildSync({
    entryPoints: [ENTRY],
    bundle: true,
    format: "iife",
    globalName: "__plottrTheme",
    platform: "browser",
    target: "es2022",
    write: false,
  });
  // The standalone HTML pages (`benchmark.html`, `privacy.html`) load this
  // bundle via a plain `<script>` and reference `getTheme` / `setTheme` /
  // `toggleTheme` from inline `<script>` blocks — there's no module system
  // there to import from. The synthetic `Object.assign(globalThis, ...)`
  // footer copies the IIFE's named exports onto the global object so the
  // inline scripts continue to resolve those names. `_core/theme.ts` itself
  // ships shim-free (consistent with the other `_core/*` modules); the
  // legacy global surface is reconstructed at bundling time, here.
  const bundle =
    "// AUTO-GENERATED by scripts/build-shared.js — do not edit by hand.\n" +
    "// Source: tools/_core/theme.ts (bundled via esbuild --format=iife).\n" +
    "// Regenerate with `npm run build` or `node scripts/build-shared.js`.\n\n" +
    result.outputFiles[0].text +
    "\nObject.assign(globalThis, __plottrTheme);\n";

  // Parse the bundle before writing. esbuild output is already
  // syntactically valid (it parsed the TS to produce it), but the
  // prepended header could in principle carry a stray comment delimiter
  // that breaks the script. `new Function(bundle)` parses without
  // executing.
  try {
    new Function(bundle);
  } catch (err) {
    throw new Error(
      "[build-shared] bundled output did not parse — leaving previous tools/shared.bundle.js untouched.\n" +
        "  Underlying error: " +
        err.message
    );
  }

  fs.writeFileSync(OUT_FILE, bundle);
  return { bytes: Buffer.byteLength(bundle) };
}

function rebuildWithLog() {
  const { bytes } = buildBundle();
  const kb = (bytes / 1024).toFixed(1);
  process.stdout.write(`[build-shared] _core/theme.ts → tools/shared.bundle.js (${kb} KB)\n`);
}

if (require.main === module) {
  rebuildWithLog();
  if (process.argv.includes("--watch")) {
    let pending = null;
    fs.watch(ENTRY, () => {
      if (pending) clearTimeout(pending);
      pending = setTimeout(() => {
        pending = null;
        try {
          rebuildWithLog();
        } catch (err) {
          process.stderr.write(`[build-shared] ${err.message}\n`);
        }
      }, 50);
    });
    process.stdout.write(`[build-shared] watching ${ENTRY} for changes…\n`);
  }
}

// FILES is preserved as a no-op export for any callers that still read it
// (none in tree, but historically the per-tool HTMLs and tests referenced
// this list).
const FILES = [];

module.exports = { buildBundle, FILES };
