#!/usr/bin/env node
// Concatenates the 12 shared browser scripts into a single tools/shared.bundle.js
// so every HTML file loads one <script> instead of twelve. The order below is the
// single source of truth — if you add a new tools/shared-*.js file, add it here,
// not to each HTML.
//
// The output is plain concatenation (no minification, no module wrapping) so top-
// level declarations remain globals, which is what every compiled tool .js and
// every test helper's vm.runInContext(...) still expects.
//
// Each segment is preceded by a banner comment with the original filename and a
// leading newline so line numbers inside a segment are easy to locate when a
// browser stack trace points at shared.bundle.js:<N>.

const fs = require("fs");
const path = require("path");

const TOOLS_DIR = path.join(__dirname, "..", "tools");
const OUT_FILE = path.join(TOOLS_DIR, "shared.bundle.js");

// Canonical load order. Derived from the per-tool HTML sequences — this is the
// union, so every tool gets every shared file whether it uses it or not. The
// size cost (~240 KB unminified) is acceptable; the contributor cost of keeping
// 9 HTML files in sync with a per-tool subset is not.
const FILES = [
  "theme.js",
  "shared.js",
  "stats.js",
  "shared-color-input.js",
  "shared-file-drop.js",
  "shared-svg-legend.js",
  "shared-core.js",
  "shared-ui.js",
  "shared-prefs.js",
  "shared-long-format.js",
  "shared-r-export.js",
  "shared-stats-tile.js",
];

function buildBundle() {
  const header =
    "// AUTO-GENERATED by scripts/build-shared.js — do not edit by hand.\n" +
    "// Source files concatenated in load order: " +
    FILES.join(", ") +
    ".\n" +
    "// Regenerate with `npm run build` or `node scripts/build-shared.js`.\n\n";

  const segments = FILES.map((name) => {
    const full = path.join(TOOLS_DIR, name);
    const src = fs.readFileSync(full, "utf8");
    const banner =
      "// ──────────────────────────────────────────────────────────────────\n" +
      "// " +
      name +
      "\n" +
      "// ──────────────────────────────────────────────────────────────────\n";
    // Trim a trailing newline from the source so the banner-to-source gap is
    // a single blank line; re-add a trailing newline after the segment.
    const body = src.endsWith("\n") ? src : src + "\n";
    return banner + body;
  });

  const bundle = header + segments.join("\n");
  fs.writeFileSync(OUT_FILE, bundle);
  return { bytes: Buffer.byteLength(bundle), fileCount: FILES.length };
}

function rebuildWithLog() {
  const { bytes, fileCount } = buildBundle();
  const kb = (bytes / 1024).toFixed(1);
  process.stdout.write(`[build-shared] ${fileCount} files → tools/shared.bundle.js (${kb} KB)\n`);
}

if (require.main === module) {
  rebuildWithLog();
  if (process.argv.includes("--watch")) {
    for (const name of FILES) {
      const full = path.join(TOOLS_DIR, name);
      // fs.watch fires on every filesystem event (can be >1 per save on some
      // editors); coalesce via a short debounce so a Vim-style atomic-write
      // rename doesn't trigger two rebuilds back-to-back.
      let pending = null;
      fs.watch(full, () => {
        if (pending) clearTimeout(pending);
        pending = setTimeout(() => {
          pending = null;
          try {
            rebuildWithLog();
          } catch (err) {
            process.stderr.write(`[build-shared] ${err.message}\n`);
          }
        }, 50);
      });
    }
    process.stdout.write("[build-shared] watching 12 shared files for changes…\n");
  }
}

module.exports = { buildBundle, FILES };
