#!/usr/bin/env node
// Vendors the chrome fonts (Fraunces + IBM Plex Mono) into tools/fonts/ so
// the deployed app makes ZERO third-party requests — the same privacy stance
// the SRI-pinned vendor/react bundle and the self-hosted Zenodo "Cite" pill
// already enforce. A fonts.gstatic.com request at runtime would be the one
// thing on the page phoning home; this script removes that by pulling the
// woff2 subsets at build-authoring time and rewriting the @font-face src to
// local paths.
//
// NOTE on SRI: @font-face url() cannot carry a Subresource-Integrity hash
// (browsers don't support `integrity` on CSS font src). Self-hosting is the
// guarantee here — the bytes live in the repo, so any change goes through
// review exactly like vendor/react. There's nothing to pin.
//
// Run manually when the font set changes: `node scripts/vendor-fonts.mjs`.
// Idempotent — re-running with the same families is a no-op diff. Not wired
// into prebuild (fonts change ~never; downloading on every CI build would add
// a network dependency to the build, which we explicitly avoid).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..");
const FONT_DIR = path.join(repoRoot, "tools", "fonts");
const CSS_OUT = path.join(repoRoot, "tools", "fonts.css");

// Variable Fraunces (normal only, full optical-size + weight range — used for
// the landing wordmark, nothing else) and three static IBM Plex Mono weights
// (the functional chrome default). display=swap so text paints immediately in
// the fallback and swaps when the woff2 lands.
const CSS_URL =
  "https://fonts.googleapis.com/css2?" +
  "family=Fraunces:opsz,wght@9..144,400..900&" +
  "family=IBM+Plex+Mono:wght@400;500;600&display=swap";

// Only these unicode subsets — Plöttr's UI is latin + latin-ext (the ö in
// "Plöttr", accented author names, °, ×, …). Skipping cyrillic / greek /
// vietnamese keeps the vendored payload small.
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

// A modern browser UA so css2 serves woff2 (it falls back to ttf for old UAs).
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

function slug(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });

  const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`css2 fetch failed: ${res.status}`);
  const css = await res.text();

  // The css2 response is a run of `/* <subset> */\n@font-face { … }` blocks.
  // Split on the subset comment so each chunk carries its own label.
  const chunks = css.split(/\/\*\s*([\w-]+)\s*\*\//).slice(1);
  const out = [];
  let downloaded = 0;

  for (let i = 0; i < chunks.length; i += 2) {
    const subset = chunks[i].trim();
    let block = chunks[i + 1];
    if (!block || !block.includes("@font-face")) continue;
    if (!KEEP_SUBSETS.has(subset)) continue;

    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
    const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
    const weight = (block.match(/font-weight:\s*([\d ]+)/) || [])[1] || "400";
    const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    if (!url) continue;

    const name = [slug(family), style, slug(weight), subset].join("_") + ".woff2";
    const dest = path.join(FONT_DIR, name);

    const fontRes = await fetch(url, { headers: { "User-Agent": UA } });
    if (!fontRes.ok) throw new Error(`font fetch failed: ${url} ${fontRes.status}`);
    fs.writeFileSync(dest, Buffer.from(await fontRes.arrayBuffer()));
    downloaded++;

    // Rewrite the remote src to the local vendored path (relative to
    // tools/fonts.css, which sits in tools/).
    block = block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url("fonts/${name}")`);
    out.push(`/* ${family} ${style} ${weight} — ${subset} */\n${block.trim()}`);
  }

  const header =
    "/* Vendored chrome fonts — generated by scripts/vendor-fonts.mjs.\n" +
    "   DO NOT edit by hand; re-run the script to regenerate. Self-hosted so\n" +
    "   the app makes no third-party font request. See the script header for\n" +
    "   why @font-face carries no SRI hash. */\n\n";
  fs.writeFileSync(CSS_OUT, header + out.join("\n\n") + "\n");

  console.log(`vendored ${downloaded} woff2 → tools/fonts/, wrote tools/fonts.css`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
