#!/usr/bin/env node
// Generates tools/version.js so the landing page can display the real
// release version instead of a hardcoded string. Run by `npm run build`
// and `npm run watch` before esbuild.
//
// Source of truth: the most recent `## [X.Y.Z] - DATE` heading in
// CHANGELOG.md. This was previously read from `git describe --tags`,
// which races the GitHub Pages deploy: the deploy workflow triggers on
// `master` push, but the tag is a separate `git push origin <tag>`.
// If the user pushes master first (release commit) and the tag a few
// seconds later, CI's `git describe` still returns the *previous* tag,
// overwrites the hand-set version in tools/version.js with the old
// number, and ships stale chrome to gh-pages even though source is
// correct. CHANGELOG is bumped synchronously with the release commit,
// so reading it eliminates the race entirely.

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

// Pure: pick the first concrete `## [X.Y.Z] - DATE` heading from a
// CHANGELOG body, returning `"vX.Y.Z"` or `null`. The `## [Unreleased]`
// heading at the top is intentionally skipped — it has no version yet,
// so its `[Unreleased]` literal can't match the digit-only group. The
// pattern requires three numeric segments separated by dots; a future
// pre-release tag like `## [1.1.0-beta]` would NOT match, falling
// through to the `git describe` fallback. That's deliberate: an
// in-progress pre-release shouldn't paint the landing-page badge yet.
function parseLatestVersion(md) {
  const match = String(md).match(/^## \[(\d+\.\d+\.\d+)\]/m);
  return match ? "v" + match[1] : null;
}

function fromChangelog() {
  try {
    return parseLatestVersion(fs.readFileSync(path.join(__dirname, "..", "CHANGELOG.md"), "utf8"));
  } catch {
    return null;
  }
}

function fromGitDescribe() {
  try {
    return execSync("git describe --tags --abbrev=0", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

// Run-when-invoked-directly guard so `require()`-ing this module from a
// test loader doesn't write to tools/version.js as a side effect.
if (require.main === module) {
  const version = fromChangelog() || fromGitDescribe() || "dev";
  const out =
    "// Auto-generated by scripts/write-version.js — do not edit.\n" +
    `window.__APP_VERSION__ = ${JSON.stringify(version)};\n`;
  const dest = path.join(__dirname, "..", "tools", "version.js");
  fs.writeFileSync(dest, out);
  console.log("version.js →", version);
}

module.exports = { parseLatestVersion, fromChangelog, fromGitDescribe };
