#!/usr/bin/env node
// Generates tools/version.js so the landing page can display the real
// git tag instead of a hardcoded string. Run by `npm run build` and
// `npm run watch` before esbuild.

const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

function describe() {
  try {
    return execSync("git describe --tags --always --dirty", {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return "dev";
  }
}

const version = describe() || "dev";
const out =
  "// Auto-generated by scripts/write-version.js — do not edit.\n" +
  `window.__APP_VERSION__ = ${JSON.stringify(version)};\n`;
const dest = path.join(__dirname, "..", "tools", "version.js");
fs.writeFileSync(dest, out);
console.log("version.js →", version);
