// Loads the shared-browser bundle (theme.js + shared.js + stats.js + all
// shared-*.js in canonical order) into a Node vm context so its pure
// functions can be tested. The bundle is generated by scripts/build-shared.js
// (runs via `pretest` in package.json), so the test harness reads the same
// artefact the browser does — single source of truth for load order.
// React-dependent components (ColorInput, FileDropZone, etc.) are stubbed out.

const fs = require("fs");
const vm = require("vm");
const path = require("path");

const toolsDir = path.join(__dirname, "../../tools");
const bundlePath = path.join(toolsDir, "shared.bundle.js");
if (!fs.existsSync(bundlePath)) {
  throw new Error(
    "components-loader: tools/shared.bundle.js is missing. Run `npm run build:shared` (or any build / test) to generate it."
  );
}
const bundleSrc = fs.readFileSync(bundlePath, "utf8");

const ctx = {
  Math,
  parseInt,
  parseFloat,
  isNaN,
  Number,
  String,
  Array,
  Object,
  console,
  // Stub out DOM APIs so shared.js loads without crashing
  setTimeout: () => {},
  document: {
    createElement: () => ({}),
    documentElement: {
      setAttribute: () => {},
      removeAttribute: () => {},
      getAttribute: () => null,
    },
    body: { appendChild: () => {}, removeChild: () => {} },
    addEventListener: () => {},
    removeEventListener: () => {},
    visibilityState: "visible",
  },
  window: {
    addEventListener: () => {},
    removeEventListener: () => {},
    matchMedia: () => ({
      matches: false,
      addEventListener: () => {},
      removeEventListener: () => {},
    }),
    dispatchEvent: () => {},
  },
  localStorage: { getItem: () => null, setItem: () => {}, removeItem: () => {} },
  CustomEvent: function () {},
  URL: { createObjectURL: () => "", revokeObjectURL: () => {} },
  Blob: function () {},
  XMLSerializer: function () {
    this.serializeToString = () => "";
  },
  // Minimal React stub — enough for the files to load without crashing
  React: {
    useState: () => [null, () => {}],
    useEffect: () => {},
    useRef: () => ({ current: null }),
    useId: () => ":r0:",
    createElement: () => null,
    memo: (fn) => fn,
    Component: class {
      constructor(props) {
        this.props = props;
        this.state = {};
      }
      setState() {}
    },
  },
};

vm.createContext(ctx);
vm.runInContext(bundleSrc, ctx);

module.exports = {
  computeLegendHeight: ctx.computeLegendHeight,
  renderSvgLegend: ctx.renderSvgLegend,
};
