// Loads `shared.bundle.js` (theme controls only) into a Node vm context
// plus `tools/_shell/svg-legend.ts` so its `computeLegendHeight` /
// `renderSvgLegend` exports can be exercised from Node without a
// browser. The bundle is regenerated by `pretest` in package.json so
// tests always see the canonical artefact the browser loads.

const vm = require("vm");
const {
  builtins,
  bundleShell,
  makeDomStubs,
  MINIMAL_REACT,
  readSharedBundleSrc,
  runCjs,
} = require("./_shell-test-utils");

const bundleSrc = readSharedBundleSrc();
const svgLegendCjs = bundleShell("_shell/svg-legend.ts");

const ctx = {
  ...builtins(),
  ...makeDomStubs(),
  React: MINIMAL_REACT,
};
vm.createContext(ctx);
vm.runInContext(bundleSrc, ctx);
const svgLegend = runCjs(ctx, svgLegendCjs);

module.exports = {
  computeLegendHeight: svgLegend.computeLegendHeight,
  renderSvgLegend: svgLegend.renderSvgLegend,
};
