// tests/helpers/render-loader.js — real React 18 + happy-dom rendering
// helpers for `tests/components.test.js`.
//
// Replaces the previous 354-line bespoke functional React mock. The
// mock was written before Vitest was on the table; under Vitest +
// happy-dom we can use the real React, the real react-dom/server, and
// the real react-dom/client and let assertions read DOM / HTML
// directly instead of reverse-engineering React-element-tree shapes
// (`el.type === "div"`, `el.children.length === 3`,
// `JSON.stringify(el).indexOf("X")`, etc.).
//
// Required environment: the consuming test file must declare
//   // @vitest-environment happy-dom
// at the top. happy-dom installs `document`, `window`, `localStorage`,
// etc. on the realm globals; this module layers `React` and a stubbed
// `ReactDOM` on top, then loads `tools/shared.bundle.js` (and
// optionally a compiled tool .js file) into the current realm so its
// top-level `function ...` / `var X = ...` declarations become
// accessible as `globalThis.X`.
//
// Public API:
//   buildContext()                        → { ctx } where ctx is
//                                            globalThis with the
//                                            shared bundle loaded.
//   loadTool(toolName)                    → { ctx, exports } where
//                                            exports holds the tool's
//                                            named chart components
//                                            (BoxplotChart, …) — same
//                                            shape the old API
//                                            returned, just sourced
//                                            from real React.
//   renderHtml(Component, props)          → static HTML string via
//                                            renderToStaticMarkup;
//                                            synchronous, no DOM
//                                            mounting, no effects.
//                                            Use this for the vast
//                                            majority of smoke tests.
//   renderWithEffects(Component, props)   → mounts via
//                                            react-dom/client +
//                                            happy-dom, runs effects
//                                            inside `act`, returns
//                                            { container, root, html }.
//                                            Use for tests that
//                                            depend on useEffect /
//                                            useLayoutEffect actually
//                                            firing.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const React = require("react");
const ReactDOMServer = require("react-dom/server");
const ReactDOMClient = require("react-dom/client");
const TestUtils = require("react-dom/test-utils");

const toolsDir = path.join(__dirname, "../../tools");

// ── Realm globals ──────────────────────────────────────────────────────
// shared.bundle.js + every compiled tool .js reference `React.…` and
// `ReactDOM.createRoot(...)` directly via the realm globals (the
// production HTML files load React via `<script src="../vendor/…">`,
// which puts it on `window`, then the shared bundle and the tool
// bundle pick it up from there). We mirror that runtime shape with
// real React 18 and a stubbed ReactDOM whose `createRoot(...).render(…)`
// is a no-op — that lets the tool .js modules execute their final
// `ReactDOM.createRoot(document.getElementById("root")).render(<App/>)`
// line without erroring on the missing `<div id="root">` and without
// trying to mount the whole app inside the test environment.

globalThis.React = React;
globalThis.ReactDOM = {
  createRoot: () => ({ render: () => {}, unmount: () => {} }),
};

// ── Shared bundle ──────────────────────────────────────────────────────
// Load once per Node process. `vm.runInThisContext(src)` runs `src` as
// a script (no module wrapper) in the current realm, so top-level
// `function …` and `var X = …` declarations attach to globalThis. The
// bundle is regenerated by `pretest` in package.json so tests always
// see the canonical artefact the browser loads.

let _bundleLoaded = false;

function ensureSharedBundleLoaded() {
  if (_bundleLoaded) return;
  const bundlePath = path.join(toolsDir, "shared.bundle.js");
  if (!fs.existsSync(bundlePath)) {
    throw new Error(
      "render-loader: tools/shared.bundle.js is missing. Run `npm run build:shared` to generate it."
    );
  }
  const bundleSrc = fs.readFileSync(bundlePath, "utf8");
  vm.runInThisContext(bundleSrc, { filename: "tools/shared.bundle.js" });
  _bundleLoaded = true;
}

function buildContext() {
  ensureSharedBundleLoaded();
  return { ctx: globalThis };
}

// ── Compiled-tool loading ──────────────────────────────────────────────
// Each tool's chart component is declared as a top-level `var BoxplotChart
// = …` (esbuild minifies but keeps the name). We wrap the tool source
// in an IIFE so its top-level `var`s are scoped to that one load — no
// collisions when multiple tools are loaded sequentially — and the
// IIFE returns a literal object naming every chart export we care
// about. `typeof X !== 'undefined'` keeps the wrapper compatible with
// tools that don't declare a particular name (volcano has no
// BarChart, scatter has no InsetBarplot, …).

function loadTool(toolName) {
  ensureSharedBundleLoaded();
  // Folder-split tools (boxplot, scatter, lineplot, aequorin, heatmap,
  // venn, upset, volcano) live under tools/<tool>/index.js; the two
  // calculators (molarity, power) keep the flat tools/<tool>.js shape.
  const flatPath = path.join(toolsDir, toolName + ".js");
  const folderPath = path.join(toolsDir, toolName, "index.js");
  const toolPath = fs.existsSync(folderPath)
    ? folderPath
    : fs.existsSync(flatPath)
      ? flatPath
      : null;
  if (toolPath == null) {
    throw new Error(
      `render-loader: cannot find tool ${toolName}. Tried ${folderPath} and ${flatPath}.`
    );
  }
  const toolSrc = fs.readFileSync(toolPath, "utf8");
  const wrapped =
    "(function() {\n" +
    toolSrc +
    "\nreturn {" +
    "BoxplotChart: typeof BoxplotChart !== 'undefined' ? BoxplotChart : undefined," +
    "BarChart: typeof BarChart !== 'undefined' ? BarChart : undefined," +
    "ScatterChart: typeof ScatterChart !== 'undefined' ? ScatterChart : undefined," +
    "Chart: typeof Chart !== 'undefined' ? Chart : undefined," +
    "InsetBarplot: typeof InsetBarplot !== 'undefined' ? InsetBarplot : undefined," +
    "PlotPanel: typeof PlotPanel !== 'undefined' ? PlotPanel : undefined," +
    "VolcanoChart: typeof VolcanoChart !== 'undefined' ? VolcanoChart : undefined," +
    "VennChart: typeof VennChart !== 'undefined' ? VennChart : undefined," +
    "UpsetChart: typeof UpsetChart !== 'undefined' ? UpsetChart : undefined," +
    "HeatmapChart: typeof HeatmapChart !== 'undefined' ? HeatmapChart : undefined," +
    "};\n})()";
  const exports = vm.runInThisContext(wrapped, { filename: toolPath });
  return { ctx: globalThis, exports };
}

// ── Render helpers ─────────────────────────────────────────────────────

// Synchronous static-HTML render. No DOM, no effects. The right tool
// for "this component compiles + lays out a sensible tree without
// throwing" smoke tests, which is 90 % of what tests/components.test.js
// asserts on. Returns the HTML string the component produces.
//
// `Component` may be either a function component or a forwardRef
// (chart components are forwardRef). Both work with `createElement`.
function renderHtml(Component, props) {
  const el = React.createElement(Component, props || {});
  return ReactDOMServer.renderToStaticMarkup(el);
}

// Mount a component into a happy-dom container with effects flushed.
// Use this when the test depends on `useEffect` / `useLayoutEffect`
// actually firing. Returns the live container (a real Element with
// querySelector, textContent, etc.) plus the root handle for unmounting.
//
// `act` from react-dom/test-utils flushes scheduled effects before
// returning, so subsequent assertions see the post-effect state. The
// `act` API logs a deprecation notice on Node 22+ but still works
// correctly; switching to React 19's `act` is a future cleanup.
function renderWithEffects(Component, props) {
  const container = globalThis.document.createElement("div");
  globalThis.document.body.appendChild(container);
  const root = ReactDOMClient.createRoot(container);
  TestUtils.act(() => {
    root.render(React.createElement(Component, props || {}));
  });
  return { container, root, html: container.innerHTML };
}

module.exports = {
  buildContext,
  loadTool,
  renderHtml,
  renderWithEffects,
  React,
  ReactDOMServer,
  ReactDOMClient,
};
