// tests/helpers/render-loader.js — real React 18 + happy-dom rendering
// helpers for `tests/components.test.js`. Uses the actual `react`,
// `react-dom/server` and `react-dom/client` packages plus happy-dom so
// assertions read DOM / HTML directly.
//
// Required environment: the consuming test file must declare
//   // @vitest-environment happy-dom
// at the top. happy-dom installs `document`, `window`, `localStorage`,
// etc. on the realm globals; this module layers `React` and a stubbed
// `ReactDOM` on top, then loads `tools/shared.bundle.js` (and
// optionally a compiled tool .js file) into the current realm so its
// top-level `function ...` / `var X = ...` declarations become
// accessible as `globalThis.X`.
//
// Public API:
//   buildContext()                        → { ctx } where ctx is
//                                            globalThis with the
//                                            shared bundle loaded.
//   loadTool(toolName)                    → { ctx, exports } where
//                                            exports holds the tool's
//                                            named chart components
//                                            (BoxplotChart, …) — same
//                                            shape the old API
//                                            returned, just sourced
//                                            from real React.
//   renderHtml(Component, props)          → static HTML string via
//                                            renderToStaticMarkup;
//                                            synchronous, no DOM
//                                            mounting, no effects.
//                                            Use this for the vast
//                                            majority of smoke tests.
//   renderWithEffects(Component, props)   → mounts via
//                                            react-dom/client +
//                                            happy-dom, runs effects
//                                            inside `act`, returns
//                                            { container, root, html }.
//                                            Use for tests that
//                                            depend on useEffect /
//                                            useLayoutEffect actually
//                                            firing.

const fs = require("fs");
const path = require("path");
const vm = require("vm");
const esbuild = require("esbuild");

const React = require("react");
const ReactDOMServer = require("react-dom/server");
const ReactDOMClient = require("react-dom/client");

// Tell React 18+ that this is a test environment so `act()` doesn't log
// "The current testing environment is not configured to support act(...)"
// on every call. Has to be set before any React render — declaring it
// here at module load happens before `renderWithEffects` runs.
globalThis.IS_REACT_ACT_ENVIRONMENT = true;

const toolsDir = path.join(__dirname, "../../tools");

// ── Realm globals ──────────────────────────────────────────────────────
// shared.bundle.js + every compiled tool .js reference `React.…` and
// `ReactDOM.createRoot(...)` directly via the realm globals (the
// production HTML files load React via `<script src="../vendor/…">`,
// which puts it on `window`, then the shared bundle and the tool
// bundle pick it up from there). We mirror that runtime shape with
// real React 18 and a stubbed ReactDOM whose `createRoot(...).render(…)`
// is a no-op — that lets the tool .js modules execute their final
// `ReactDOM.createRoot(document.getElementById("root")).render(<App/>)`
// line without erroring on the missing `<div id="root">` and without
// trying to mount the whole app inside the test environment.

globalThis.React = React;
globalThis.ReactDOM = {
  createRoot: () => ({ render: () => {}, unmount: () => {} }),
};

// ── Shared bundle ──────────────────────────────────────────────────────
// Load once per Node process. `vm.runInThisContext(src)` runs `src` as
// a script (no module wrapper) in the current realm, so top-level
// `function …` and `var X = …` declarations attach to globalThis. The
// bundle is regenerated by `pretest` in package.json so tests always
// see the canonical artefact the browser loads.

let _bundleLoaded = false;

function ensureSharedBundleLoaded() {
  if (_bundleLoaded) return;
  // shared.bundle.js carries the IIFE-bundled `_core/theme.ts` so the
  // inline no-FOUC `<script>` in each HTML can call `setTheme` /
  // `getTheme` before first paint. Loaded into the test runner's realm
  // via `runInThisContext` so the synthetic `Object.assign(globalThis,
  // __plottrTheme)` footer (added by `scripts/build-shared.js`) puts the
  // theme functions on the runner's globalThis.
  const bundlePath = path.join(toolsDir, "shared.bundle.js");
  if (!fs.existsSync(bundlePath)) {
    throw new Error(
      "render-loader: tools/shared.bundle.js is missing. Run `npm run build:shared` to generate it."
    );
  }
  const bundleSrc = fs.readFileSync(bundlePath, "utf8");
  vm.runInThisContext(bundleSrc, { filename: "tools/shared.bundle.js" });

  // Bundle and run `_core/stats/*` and `_core/shared.ts` with a synthetic
  // `Object.assign(globalThis, …)` footer so the realm gets every named
  // export on globalThis — the components tests (and a handful of
  // chart-bundle paths) reach for `globalThis.parseRaw`,
  // `globalThis.buildExportSvg`, `globalThis.PALETTE`, etc. without
  // importing them. `globalName` collects the IIFE's exports into one
  // object so a single `Object.assign` per bundle copies them across.
  const coreStats = esbuild.buildSync({
    entryPoints: [path.join(toolsDir, "_core/stats/index.ts")],
    bundle: true,
    format: "iife",
    globalName: "__plottrStats",
    platform: "neutral",
    target: "es2022",
    write: false,
  }).outputFiles[0].text;
  vm.runInThisContext(coreStats + "\nObject.assign(globalThis, __plottrStats);\n", {
    filename: "tools/_core/stats/index.ts",
  });

  const coreShared = esbuild.buildSync({
    entryPoints: [path.join(toolsDir, "_core/shared.ts")],
    bundle: true,
    format: "iife",
    globalName: "__plottrShared",
    platform: "neutral",
    target: "es2022",
    write: false,
  }).outputFiles[0].text;
  vm.runInThisContext(coreShared + "\nObject.assign(globalThis, __plottrShared);\n", {
    filename: "tools/_core/shared.ts",
  });

  // `_shell` modules — bundle the barrel via esbuild and lift its named
  // exports onto globalThis so `sc.DataPreview` / `sc.X` call sites in
  // tests/components.test.js resolve through the same surface that real
  // consumers use. Adding a new shared export means appending to this
  // `names` list (and the barrel itself); no separate registration block.
  const SHELL_GLOBALS = [
    {
      src: path.join(toolsDir, "_shell/index.ts"),
      names: [
        "ActionsPanel",
        "BaseStyleControls",
        "CldLabels",
        "ColorInput",
        "ColumnRoleEditor",
        "CommaFixBanner",
        "DataPreview",
        "DatasheetIcon",
        "DetectedSeparatorBadge",
        "DiscretePaletteRow",
        "DownloadTiles",
        "ErrorBoundary",
        "FILE_LIMIT_BYTES",
        "FILE_WARN_BYTES",
        "FileDropZone",
        "FilterCheckboxPanel",
        "FormulaInjectionBanner",
        "GroupColorEditor",
        "HowTo",
        "HowToCard",
        "NumberInput",
        "PageHeader",
        "ParseErrorBanner",
        "PlotSidebar",
        "PlotToolShell",
        "PrefsPanel",
        "RenameReorderPanel",
        "STATS_POSTHOC_REGISTRY",
        "STATS_TESTS_FOR_K",
        "STATS_TESTS_FOR_K2",
        "STATS_TEST_REGISTRY",
        "ScrollablePlotCard",
        "SignificanceBrackets",
        "SliderControl",
        "StatsTable",
        "StatsTile",
        "StepNavBar",
        "UploadPanel",
        "applyDiscretePalette",
        "assignBracketLevels",
        "buildRScript",
        "buildRScriptForPower",
        "computePowerFromData",
        "describeSeparator",
        "detectLongFormat",
        "formatRNumber",
        "formatRVector",
        "normalizeHexColor",
        "resolveDiscretePalette",
        "sanitizeRComment",
        "sanitizeRString",
        "scrollDisclosureIntoView",
      ],
    },
  ];
  for (const { src, names } of SHELL_GLOBALS) {
    const built = esbuild.buildSync({
      entryPoints: [src],
      bundle: true,
      format: "cjs",
      platform: "neutral",
      jsx: "transform",
      write: false,
      external: ["react", "react-dom"],
    }).outputFiles[0].text;
    const moduleObj = { exports: {} };
    // The bundled output references React via `require("react")`; bridge
    // that to the same React module the test file uses.
    const fakeRequire = (id) => {
      if (id === "react") return React;
      if (id === "react-dom") return require("react-dom");
      throw new Error(`render-loader: unexpected require(${id})`);
    };
    new Function("module", "exports", "require", "React", built)(
      moduleObj,
      moduleObj.exports,
      fakeRequire,
      React
    );
    for (const name of names) {
      globalThis[name] = moduleObj.exports[name];
    }
  }

  _bundleLoaded = true;
}

function buildContext() {
  ensureSharedBundleLoaded();
  return { ctx: globalThis };
}

// ── Compiled-tool loading ──────────────────────────────────────────────
// Bundles each tool's `app.tsx` in-memory via `esbuild.buildSync` with
// `format=iife`, so the chart components declared at the top level of
// the tool's source become accessible as IIFE-return values. (Same
// pattern as `tests/helpers/venn-loader.js` for venn's `helpers.ts`
// barrel.) Build cost is ~50 ms per tool; the result is memoised so
// repeated `loadTool("boxplot")` calls inside one test run only build
// once.
//
// `typeof X !== 'undefined'` in the IIFE return keeps the wrapper
// compatible with tools that don't declare a particular name (volcano
// has no BarChart, scatter has no InsetBarplot, …).

const _toolBundleCache = new Map();

function loadTool(toolName) {
  ensureSharedBundleLoaded();
  if (_toolBundleCache.has(toolName)) {
    const cached = _toolBundleCache.get(toolName);
    return { ctx: globalThis, exports: cached };
  }

  // Plot tools: tools/<tool>/app.tsx; calculators: tools/<tool>-app.tsx.
  const folderApp = path.join(toolsDir, toolName, "app.tsx");
  const flatApp = path.join(toolsDir, toolName + "-app.tsx");
  const appPath = fs.existsSync(folderApp) ? folderApp : fs.existsSync(flatApp) ? flatApp : null;
  if (appPath == null) {
    throw new Error(
      `render-loader: cannot find tool ${toolName}. Tried ${folderApp} and ${flatApp}.`
    );
  }

  // Bundle in IIFE format so vm.runInThisContext can parse the result
  // (ESM `export` would error). The wrapping `(function() {…})()`
  // gives us a clean lexical scope per tool — repeated loads with
  // different sources don't pollute globalThis with stale `var`s.
  const result = esbuild.buildSync({
    entryPoints: [appPath],
    bundle: true,
    write: false,
    format: "iife",
    jsx: "transform",
    minify: false,
    sourcemap: false,
    // shared.bundle.js already exposes React, ReactDOM, the shared-*.js
    // globals, and the chart-internal helpers as realm globals; we don't
    // want esbuild to inline them again. None of the tool sources use
    // `import React from "react"` so esbuild treats `React` as a free
    // variable and emits it bare — which is what we want.
    target: "es2022",
  });
  const compiled = result.outputFiles[0].text;

  // Wrap the compiled IIFE so it returns the chart-component handles.
  // The compiled output already starts with `(() => {` (the IIFE);
  // we splice in a `return { … }` before the closing `})();`.
  const closingIdx = compiled.lastIndexOf("})();");
  if (closingIdx < 0) {
    throw new Error(`render-loader: unexpected esbuild output for ${toolName}`);
  }
  const returnObj =
    "return {" +
    "BoxplotChart: typeof BoxplotChart !== 'undefined' ? BoxplotChart : undefined," +
    "BarChart: typeof BarChart !== 'undefined' ? BarChart : undefined," +
    "ScatterChart: typeof ScatterChart !== 'undefined' ? ScatterChart : undefined," +
    "Chart: typeof Chart !== 'undefined' ? Chart : undefined," +
    "InsetBarplot: typeof InsetBarplot !== 'undefined' ? InsetBarplot : undefined," +
    "PlotPanel: typeof PlotPanel !== 'undefined' ? PlotPanel : undefined," +
    "VolcanoChart: typeof VolcanoChart !== 'undefined' ? VolcanoChart : undefined," +
    "VennChart: typeof VennChart !== 'undefined' ? VennChart : undefined," +
    "UpsetChart: typeof UpsetChart !== 'undefined' ? UpsetChart : undefined," +
    "HeatmapChart: typeof HeatmapChart !== 'undefined' ? HeatmapChart : undefined," +
    "App: typeof App !== 'undefined' ? App : undefined," +
    "};";
  const withReturn = compiled.slice(0, closingIdx) + returnObj + compiled.slice(closingIdx);
  const exports = vm.runInThisContext(withReturn, { filename: appPath });
  _toolBundleCache.set(toolName, exports);
  return { ctx: globalThis, exports };
}

// ── Render helpers ─────────────────────────────────────────────────────

// Synchronous static-HTML render. No DOM, no effects. The right tool
// for "this component compiles + lays out a sensible tree without
// throwing" smoke tests, which is 90 % of what tests/components.test.js
// asserts on. Returns the HTML string the component produces.
//
// `Component` may be either a function component or a forwardRef
// (chart components are forwardRef). Both work with `createElement`.
function renderHtml(Component, props) {
  const el = React.createElement(Component, props || {});
  return ReactDOMServer.renderToStaticMarkup(el);
}

// Mount a component into a happy-dom container with effects flushed.
// Use this when the test depends on `useEffect` / `useLayoutEffect`
// actually firing. Returns the live container (a real Element with
// querySelector, textContent, etc.) plus the root handle for unmounting.
//
// `act` flushes scheduled effects before returning, so subsequent
// assertions see the post-effect state. React 18.3+ ships a stable
// `React.act` — preferred over the older `react-dom/test-utils.act`
// (which logs `ReactDOMTestUtils.act is deprecated in favor of
// React.act` on Node 22+).
function renderWithEffects(Component, props) {
  const container = globalThis.document.createElement("div");
  globalThis.document.body.appendChild(container);
  const root = ReactDOMClient.createRoot(container);
  React.act(() => {
    root.render(React.createElement(Component, props || {}));
  });
  return { container, root, html: container.innerHTML };
}

module.exports = {
  buildContext,
  loadTool,
  renderHtml,
  renderWithEffects,
  React,
  ReactDOMServer,
  ReactDOMClient,
};
