// Loads tools/stats.js as a require()-able CommonJS module and exposes
// its statistical primitives (distributions, tests, descriptive helpers,
// effect sizes, post-hocs, p-value adjustments).
//
// Why require() instead of vm.runInContext: Stryker's per-test coverage
// instrumentation injects a `__stryker__` global into mutated source to
// record which tests touch which lines. Writes from inside a vm child
// context land on a different `__stryker__` than the test runner sees,
// so the property tests would look like they have zero coverage of
// stats.js mutants and Stryker would skip them. require() makes the
// file part of Node's module dependency graph, which Stryker can trace.
//
// stats.js is plain ES2022 script-mode JS — it declares functions and
// `const` bindings at top level, expecting them to be visible as globals.
// Inside a CommonJS module those declarations stay in module scope, so
// we append a footer that mirrors every top-level declaration onto
// `module.exports`. The footer is auto-generated by scanning the source
// for `function NAME(` and `const NAME =` (top of line, public-facing
// names only) — no hand-maintained export list to drift from the source.

const fs = require("fs");
const path = require("path");
const { readStatsSource } = require("./stats-source");

const statsRaw = readStatsSource();

// Auto-generate the exports footer. Match `function name(` and
// `const name = …` at the start of a line. Underscore-prefixed names
// (e.g. `_wprob`, `_wprob_upper`) are conventionally internal helpers,
// but `tests/stats.test.js` exercises them directly to pin the
// closed-form complement identity for k=2, so we export them too. No
// hand-maintained list to drift from the source.
const declRe = /^(?:function\s+(\w+)\s*\(|const\s+(\w+)\s*=)/gm;
const seen = new Set();
const exportNames = [];
for (const m of statsRaw.matchAll(declRe)) {
  const name = m[1] || m[2];
  if (!name || seen.has(name)) continue;
  seen.add(name);
  exportNames.push(name);
}

const footer =
  "\n// auto-generated by tests/helpers/stats-loader.js\n" +
  exportNames.map((n) => `module.exports.${n} = ${n};`).join("\n") +
  "\n";

// Write the wrapped source to a stable temp path under tests/.tmp/ and
// require() it. Cache-bust on every loader invocation so Stryker
// mutations propagate through Node's module cache.
const tmpDir = path.join(__dirname, "../.tmp");
fs.mkdirSync(tmpDir, { recursive: true });
const tmpStatsFile = path.join(tmpDir, "stats.cjs");
fs.writeFileSync(tmpStatsFile, statsRaw + footer);
delete require.cache[tmpStatsFile];
const stats = require(tmpStatsFile);

// Mirror the require()'d module on a `ctx` property so legacy test
// code that reaches in via `loader.ctx.fooName` (the prior vm-context
// pattern) keeps working without a sweep through every reference.
module.exports = { ...stats, ctx: stats };
